name: Main Taski Workflow
on:
  push:
    branches:
      -main
jobs:
  checkout-and-print-tree:
    runs-on: ubuntu-latest
    sreps:
      - name: Check out repository code
        uses: actions/checkout@v
      - name: Print project tree
        run: tree .
